### ISSUE TITLE
issue when using jar in android

### ISSUE THREAD

**Issue by prakashmeghan** [intrinio/intrinio-realtime-java-sdk#3]
following issue occurred when using jar in android -
java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
                                                                                    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
                                                                                    at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:964)

**Comment by civilframe** [comment]
See https://github.com/intrinio/intrinio-realtime-java-sdk/releases/tag/v2.1.0 for fix. Thank you!
